dist: trusty
sudo: required

# Required for correct setup of virtualenvwrapper
language: python

env:
 - ZSH_VERSION=5.3.1 URL=https://downloads.sourceforge.net/project/zsh/zsh/5.3.1/zsh-5.3.1.tar.xz
 - ZSH_VERSION=5.2 URL=https://downloads.sourceforge.net/project/zsh/zsh/5.2/zsh-5.2.tar.xz
 - ZSH_VERSION=5.1.1 URL=https://downloads.sourceforge.net/project/zsh/zsh/5.1.1/zsh-5.1.1.tar.xz
 - ZSH_VERSION=5.0.8 URL=https://downloads.sourceforge.net/project/zsh/zsh/5.0.8/zsh-5.0.8.tar.gz

addons:
  apt:
    packages:
    - build-essential

before_install:
    - if ! [[ -d "$HOME/zsh" ]]; then wget $URL; fi
    - if ! [[ -d "$HOME/zsh" ]]; then tar -xf zsh-$ZSH_VERSION.tar.*; fi
    - if ! [[ -d "$HOME/zsh" ]]; then cd zsh-$ZSH_VERSION; fi
    - if ! [[ -d "$HOME/zsh" ]]; then ./configure --prefix=$HOME/zsh; fi
    - if ! [[ -d "$HOME/zsh" ]]; then make; fi
    - if ! [[ -d "$HOME/zsh" ]]; then make install; fi
    - cd -
    - export PATH="$HOME/zsh/bin:$PATH"

install:
    - pip install virtualenvwrapper

before_script:
    - mkdir -p ~/bin
    - curl -L https://raw.githubusercontent.com/molovo/revolver/master/revolver > ~/bin/revolver
    - curl -L https://github.com/molovo/zunit/releases/download/v0.8.1/zunit > ~/bin/zunit
    - chmod u+x ~/bin/{revolver,zunit}

script:
    - zunit --verbose

cache:
  directories:
  - $HOME/zsh
